### PR TITLE
ghc 7.10.1 Fixes 

### PR DESCRIPTION
**Pull request by agomezl**
The fixes are pretty simple
- `Data a => Data (Identity a)` is now in `Data.Data` so the instance definition in  `Codec.TPTP.Base` 
  is no longer needed
- `(<$>)` is now on `Prelude` so I just hid it.

I test this with `ghc-7.8.3` and `ghc-7.10.1`

### CODE REVIEW

**Comment by DanielSchuessler** [comment]
Thanks again!

**Comment by msakai** [comment]
I would be appreciated if you could upload a new version with this fix to Hackage.

**Comment by DanielSchuessler** [comment]
Done!

**Comment by msakai** [comment]
Thanks!!

**Pull request merged**
