### PR TITLE
A naive solution for issue (1)

### LINKED ISSUE #1: <formula_data> missing definitions
I was trying to parse this formula

```
cnf(refute_0_9, plain, (hates(butler, X_8) | richer(X_8, agatha)),
    inference(subst, [], [refute_0_8 : [bind(X, $fot(X_8))]])).
```

And get this error

```
tstp2agda: Parse error, pos: [RP,RP,Rbrack,Rbrack,RP,RP,Dot]
```

After some digging, I found that the error is related with `$fot(X_8)` and the
way `<formula_data>` is defined in `Parser.y`

```
formula_data :: {GData}
formula_data  : dollar_word lp fof_formula  rp { GFormulaData $1 $3 }
              -- too ambiguous | dollar_word lp cnf_formula  rp { GFormulaData $1 $3 }
```

Which differs with the one in the TPTP syntax

```
<formula_data> ::= $thf(<thf_formula>) | $tff(<tff_formula>) |
                   $fof(<fof_formula>) | $cnf(<cnf_formula>) |
                   $fot(<term>)
```

I guess this could be fixed with something like

```
%token
 ...
 -- Some new tokens
 tok_fd_fof             { DollarWord "$fot" }
 tok_fd_cnf             { DollarWord "$cnf" }
 ...
%%
...
-- A somehow better definition for <formula_data>
formula_data :: {GData}
formula_data  :  tok_fd_fof lp fof_formula  rp { GFormulaData "$fof" $3 }
               | tok_fd_cnf lp cnf_formula  rp { GFormulaData "$cnf" $3 }
```

But this still left out the case with `$fot(<term>)` since this may need an
extra data constructor for `GData`  thus not actually fixing the problem.
what do you think is the proper  way to solve this issue?

Thanks.

### PR DESCRIPTION
**Pull request by agomezl**
hopefully fixes #1

### CODE REVIEW

**Comment by DanielSchuessler** [comment]
Thanks for your contributions! Just wanted to say that I didn't have the time yet to refresh my knowledge of the TPTP syntax and consider the consequences of this change.

**Comment by msakai** [comment]
I'll take a look at it.

**Comment by msakai** [comment]
We need to update functions that handle `GFormulaTerm` to handle newly introduced `GFormulaTerm`.

**Comment by msakai** [comment]
I'm working on in #19.

**Review by msakai — APPROVED** [review]
It looks good to me with several additional changes in #19.

**Pull request merged**
